### PR TITLE
Added generate password flow

### PR DESCRIPTION
**Pull request by jgogstad**
It's handy to have a shortcut for generating new passwords when the browser plugin doesn't play along. Added `lpgenerate [password_length]`.

### CODE REVIEW

**Comment by hawkins** [comment]
Does this also support toggling special characters, or capitalization / number requirements?

**Comment by jgogstad** [comment]
It delegates generation to the lastpass cli util, that util has default everything on. There is currently a bug in this PR, the generated passworded is by default stored in lastpass under a random name, will commit a fix when I get back to this.

**Comment by stuartcryan** [comment]
Howdy @jgogstad,
I finally have a bit of a breather and am looking through pull requests and the like over the Christmas break. How were you thinking of handling generating under a non-default name?
Cheers,
Stuart

**Comment by jgogstad** [comment]
Generate a new password under a random name and then do `lpass rm <unique-name>` after. I never got around to implement it, and now I've changed to 1password. The macOS integration is miles ahead of Lastpass.

Closing PR as it's not ready for merge

**Pull request closed without merging**
